interface Frame {
  x: number;
  y: number;
  w: number;
  h: number;
}

/**
 * Sprite sheet access. The sheet is generated by `pnpm sprites` from
 * palette + shape descriptors; sprites face +x and rotate at draw time.
 * Rendering falls back to rects until the sheet finishes loading.
 */
export class SpriteSheet {
  private image: HTMLImageElement | null = null;
  private frames: Record<string, Frame> = {};

  async load(): Promise<void> {
    try {
      const meta = (await (await fetch('/sprites.meta.json')).json()) as Record<string, Frame>;
      const img = new Image();
      img.src = '/sprites.png';
      await img.decode();
      this.frames = meta;
      this.image = img;
    } catch {
      // Missing sheet is fine — placeholder rects render instead.
    }
  }

  /** Draw sprite centred at (x, y), rotated. Returns false if unavailable. */
  draw(ctx: CanvasRenderingContext2D, name: string, x: number, y: number, rot: number): boolean {
    const frame = this.frames[name];
    if (!this.image || !frame) return false;
    ctx.save();
    ctx.translate(Math.floor(x), Math.floor(y));
    ctx.rotate(rot);
    ctx.drawImage(
      this.image,
      frame.x,
      frame.y,
      frame.w,
      frame.h,
      -Math.floor(frame.w / 2),
      -Math.floor(frame.h / 2),
      frame.w,
      frame.h,
    );
    ctx.restore();
    return true;
  }
}
