import { arterialCoord } from './roads.js';
import { generateCity } from './generate.js';
import type { WorldgenParams } from './params.js';
import type { CityMap, Landmark } from './types.js';

/**
 * B1 of the streaming plan (WORLDGEN.md §11.2): a cell-keyed store over the
 * unbounded world. The unit is the arterial-lattice cell — the same unit
 * generation is local to — and each cell's tiles and features are extracted
 * from a PADDED window generated by the ordinary `generateCity`, with the
 * pad chosen to exceed the window rim's edge effects. That buys the
 * equality guarantee for free: the store cannot disagree with a window
 * because it is made of windows — store.test.ts holds them bit-identical
 * on window interiors.
 *
 * Correctness-first, deliberately: a true per-cell rasteriser would be
 * ~300× cheaper per cell and can replace the padded-window path behind
 * this same API without changing a caller.
 */

interface StoredCell {
  /** Global tile rect this cell covers (arterial centre to centre). */
  gx: number;
  gy: number;
  w: number;
  h: number;
  tiles: Uint8Array;
  /** Landmarks whose stamped rect starts inside this cell, GLOBAL tiles. */
  landmarks: Landmark[];
  /** LRU clock. */
  touched: number;
}

export class WorldStore {
  private readonly cells = new Map<string, StoredCell>();
  private clock = 0;

  constructor(
    private readonly seed: number,
    private readonly params: WorldgenParams,
    /** Cells kept before least-recently-used eviction. */
    private readonly maxCells = 64,
  ) {}

  /** Lattice index of the arterial interval containing g on an axis. */
  private latticeIndex(axis: 'x' | 'y', g: number): number {
    const sp = this.params.arterialSpacing;
    let k = Math.floor(g / sp);
    while (arterialCoord(this.seed, axis, k, sp) > g) k--;
    while (arterialCoord(this.seed, axis, k + 1, sp) <= g) k++;
    return k;
  }

  private ensureCell(i: number, j: number): StoredCell {
    const key = `${i}:${j}`;
    const hit = this.cells.get(key);
    if (hit) {
      hit.touched = ++this.clock;
      return hit;
    }
    const sp = this.params.arterialSpacing;
    const gx = arterialCoord(this.seed, 'x', i, sp);
    const gy = arterialCoord(this.seed, 'y', j, sp);
    const w = arterialCoord(this.seed, 'x', i + 1, sp) - gx;
    const h = arterialCoord(this.seed, 'y', j + 1, sp) - gy;

    // Pad past the rim: carving passes suppress within ~one cell span of a
    // window edge, so the pad holds this cell's rect clear of all of it.
    const pad = sp * 2;
    const win: WorldgenParams = {
      ...this.params,
      windowX: gx - pad,
      windowY: gy - pad,
      widthTiles: w + pad * 2,
      heightTiles: h + pad * 2,
    };
    const m: CityMap = generateCity(this.seed, win);

    const tiles = new Uint8Array(w * h);
    for (let ty = 0; ty < h; ty++) {
      for (let tx = 0; tx < w; tx++) {
        tiles[ty * w + tx] = m.tiles[(ty + pad) * m.widthTiles + (tx + pad)] as number;
      }
    }
    const landmarks = m.landmarks
      .filter((l) => l.x >= pad && l.x < pad + w && l.y >= pad && l.y < pad + h)
      .map((l) => ({
        ...l,
        x: l.x - pad + gx,
        y: l.y - pad + gy,
        doorX: l.doorX + (gx - pad) * 16,
        doorY: l.doorY + (gy - pad) * 16,
      }));

    const cell: StoredCell = { gx, gy, w, h, tiles, landmarks, touched: ++this.clock };
    this.cells.set(key, cell);
    if (this.cells.size > this.maxCells) {
      let oldest: string | null = null;
      let oldestTouch = Infinity;
      for (const [k, c] of this.cells) {
        if (c.touched < oldestTouch) {
          oldestTouch = c.touched;
          oldest = k;
        }
      }
      // Eviction is free to be wrong-headed but never wrong: cells are pure
      // functions, so regenerating one later reproduces it exactly
      // (store.test.ts pins that too).
      if (oldest) this.cells.delete(oldest);
    }
    return cell;
  }

  /** Tile at a GLOBAL coordinate, generated on demand. */
  tileAt(gx: number, gy: number): number {
    const i = this.latticeIndex('x', gx);
    const j = this.latticeIndex('y', gy);
    const cell = this.ensureCell(i, j);
    return cell.tiles[(gy - cell.gy) * cell.w + (gx - cell.gx)] as number;
  }

  /** Landmarks whose stamp begins inside a GLOBAL tile rect. */
  landmarksIn(gx: number, gy: number, w: number, h: number): Landmark[] {
    const out: Landmark[] = [];
    const i0 = this.latticeIndex('x', gx);
    const i1 = this.latticeIndex('x', gx + w - 1);
    const j0 = this.latticeIndex('y', gy);
    const j1 = this.latticeIndex('y', gy + h - 1);
    for (let j = j0; j <= j1; j++) {
      for (let i = i0; i <= i1; i++) {
        for (const l of this.ensureCell(i, j).landmarks) {
          if (l.x >= gx && l.x < gx + w && l.y >= gy && l.y < gy + h) out.push(l);
        }
      }
    }
    return out;
  }

  /** Resident cell count, for tests and budgets. */
  size(): number {
    return this.cells.size;
  }
}
