import { chromium } from 'playwright';
import { readFileSync, writeFileSync } from 'node:fs';
const [file, out, sx, sy, sw, sh, zoomS] = process.argv.slice(2);
const zoom = Number(zoomS ?? 1);
const b64 = readFileSync(file).toString('base64');
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage();
const data = await p.evaluate(async ({ b64, sx, sy, sw, sh, zoom }) => {
  const img = new Image();
  img.src = 'data:image/png;base64,' + b64;
  await img.decode();
  const c = document.createElement('canvas');
  c.width = sw * zoom; c.height = sh * zoom;
  const x = c.getContext('2d');
  x.imageSmoothingEnabled = false;
  x.drawImage(img, sx, sy, sw, sh, 0, 0, sw * zoom, sh * zoom);
  return c.toDataURL('image/png');
}, { b64, sx: +sx, sy: +sy, sw: +sw, sh: +sh, zoom });
writeFileSync(out, Buffer.from(data.split(',')[1], 'base64'));
await b.close();
console.log('wrote', out);
